- name: Generate Doxygen Documentation
  working-directory: ./Documentation
  run: doxygen Doxyfile

- name: Deploy to gh-pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./Documentation/docs/html  # ← ÇA DOIT ÊTRE ÇA
